controller_list:
  - name: "arm"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [chassis__arm1, joint1_arm1, joint2_arm1, joint3_arm1, gripper_left, gripper_right, chassis__arm2, joint1_arm2, joint2_arm2]

    