<?xml version="1.0"?>

<robot name="mrm" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.5"/>
  <xacro:property name="chassisLength" value="2"/>
  <xacro:property name="chassisWidth" value="1"/>
  <xacro:property name="chassisMass" value="250"/>

  <xacro:property name="casterRadius" value="0.25"/>
  <xacro:property name="casterMass" value="25"/>

  <xacro:property name="wheelWidth" value="0.25"/>
  <xacro:property name="wheelRadius" value="0.5"/>
  <xacro:property name="wheelPos" value="1"/>
  <xacro:property name="wheelMass" value="25"/>

  <!--<xacro:include filename="$(find mrm_description)/urdf/mrm_gazebo.xacro"/>-->
  <xacro:include filename="$(find mrm_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mrm_description)/urdf/macros.xacro" />

  <!--start of description of robot-->

  <link name="footprint" />
  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>
  
  <!--Body of robot-->

  <link name="chassis">
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	   <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	   <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="grey"/>
    </visual>
      
    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}"   z="${chassisHeight}"/>
    </inertial>
  </link>

  <joint name="fixed" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
  </joint>

  <link name="caster_wheel">
    <collision>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	   <sphere radius="${casterRadius}"/>
      </geometry>
    </collision>
  
    <visual> 
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	   <sphere radius="${casterRadius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
 </link>

<!--Two wheels of robot(properties refer to macros.xacro)-->
 <wheel lr="left" tY="-1"/>
 <wheel lr="right" tY="1"/>

<!--description of robot arm1 (gripping arm)-->
 <joint name="chassis__arm1" type="revolute">
    <origin xyz="0.2 0 0.75" rpy="0 0 0"  />
    <parent link="chassis"/>
    <child link="link1_arm1"/>
    <axis xyz="0 0 1" rpy="0 0 0" />
    <limit effort="1000" lower="${-PI/2}" upper="${PI/2}" velocity="0.5" />
 </joint>

 <transmission name="trans_chassis__arm1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="chassis__arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_chassis__arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="link1_arm1">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	   <cylinder length="0.9" radius="0.3"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	   <cylinder length="0.9" radius="0.3"/>
      </geometry>
      <material name="orange"/>
    </visual>
      
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="35"/>
      <cylinder_inertia m="35" r="0.3" h="0.9"/>
    </inertial>

    <inertial>
        <mass value="10" />
        <origin rpy="${PI/2} 0 0" xyz="-0.165 0.262 0.45" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="${PI/2} 0 0" xyz="-0.165 0.26 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Base_link1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="${PI/2} 0 0" xyz="-0.165 0.26 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Base_link1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>

    <inertial>
        <mass value="10" />
        <origin rpy="${PI/2} 0 ${PI}" xyz="0.165 -0.26 0.45" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="${PI/2} 0 ${PI}" xyz="0.165 -0.26 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Base_link1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="${PI/2} 0 ${PI}" xyz="0.165 -0.26 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Base_link1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>
 </link>
  
 <joint name="joint1_arm1" type="revolute">
    <origin xyz="0 0 0.6" rpy="0 0 0"  />
    <parent link="link1_arm1"/>
    <child link="link2_arm1"/>
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="1000" lower="-1" upper="0" velocity="0.5" />
 </joint>

 <transmission name="trans_joint1_arm1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1_arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint1_arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="link2_arm1">  
    <inertial>
        <mass value="10" />
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 0.14 1.11" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 0.14 1.11" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Lower_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 0.14 1.11" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Lower_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>

    <inertial>
        <mass value="10" />
        <origin rpy="0 ${PI} ${PI/2}" xyz="0.185 -0.14 1.11" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="0 ${PI} ${PI/2}" xyz="0.185 -0.14 1.11" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Lower_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>


    <visual>
        <origin rpy="0 ${PI} ${PI/2}" xyz="0.185 -0.14 1.11" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Lower_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>
 </link>

 <joint name="joint2_arm1" type="revolute">
    <origin xyz="0 0 1" rpy="0 0 0"  />
    <parent link="link2_arm1"/>
    <child link="link3_arm1"/>
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="1000" lower="${-PI/2}" upper="0" velocity="0.5" />
 </joint>

 <transmission name="trans_joint2_arm1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2_arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint2_arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="link3_arm1">  
    <inertial>
        <mass value="9" />
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 0 0.7" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 0 0.7" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Center_arm.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 0 0.7" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Center_arm.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>

    <inertial>
        <mass value="9" />
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 -0.15 0.7" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 -0.15 0.7" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Center_arm.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.15 -0.15 0.7" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Center_arm.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>
 </link>

 <joint name="joint3_arm1" type="revolute">
    <origin xyz="0 0 0.56" rpy="0 0 0"  />
    <parent link="link3_arm1"/>
    <child link="link4_arm1"/>
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="1000" lower="0" upper="${PI/2}" velocity="0.5" />
 </joint>

 <transmission name="trans_joint3_arm1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3_arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint3_arm1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="link4_arm1">  
    <inertial>
        <mass value="5" />
        <origin rpy="0 ${PI} ${PI/2}" xyz="0.13 -0.15 0.45" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="0 ${PI} ${PI/2}" xyz="0.13 -0.15 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="0 ${PI} ${PI/2}" xyz="0.13 -0.15 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>

    <inertial>
        <mass value="5" />
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.135 0.15 0.45" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.135 0.15 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_right.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="0 ${PI} ${-PI/2}" xyz="-0.135 0.15 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_right.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="orange"/>
    </visual>

    <inertial>
        <mass value="3.5" />
        <origin rpy="0 0 0" xyz="-0.12 -0.25 0.45" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="0 0 0" xyz="-0.12 -0.25 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_servo_mount.stl" scale="0.007 0.007 0.007"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="0 0 0" xyz="-0.12 -0.25 0.45" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_servo_mount.stl" scale="0.007 0.007 0.007"/>
        </geometry>
        <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="-0.1 0 0.65" rpy="0 0 0"/>
      <geometry>
	   <box size="0.05 0.5 0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.1 0 0.65" rpy="0 0 0"/>
      <geometry>
	   <box size="0.05 0.5 0.2"/>
      </geometry>
      <material name="orange"/>
    </visual>
      
    <inertial>
      <origin xyz="-0.1 0 0.65" rpy="0 0 0"/>
      <mass value="3.5"/>
      <box_inertia m="3.5" x="0.05" y="0.5" z="0.2"/>
    </inertial>
 </link>

 <joint name="gripper_right" type="revolute">
    <origin xyz="0 0.25 0.8" rpy="0 0 0"  />
    <parent link="link4_arm1"/>
    <child link="rightgripper"/>
    <axis xyz="1 0 0" rpy="0 0 0" />
    <limit effort="1000" lower="-0.3" upper="0.2" velocity="0.3" />
 </joint>

 <transmission name="trans_gripper_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_right">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_gripper_right">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="rightgripper">  
    <inertial>
        <mass value="2" />
        <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 -0.05 -0.1" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 -0.05 -0.1" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Gripper_arm1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 -0.05 -0.1" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Gripper_arm1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="red"/>
    </visual>
 </link>

 <joint name="gripper_left" type="revolute">
    <origin xyz="0 -0.25 0.8" rpy="0 0 0"  />
    <parent link="link4_arm1"/>
    <child link="leftgripper"/>
    <axis xyz="1 0 0" rpy="0 0 0" />
    <limit effort="1000" lower="-0.2" upper="0.3" velocity="0.3" />
 </joint>

 <transmission name="trans_gripper_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_left">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_gripper_left">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="leftgripper">  
    <inertial>
        <mass value="2" />
        <origin rpy="${PI/2} 0 ${PI/2}" xyz="-0.1 0.05 -0.1" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="${PI/2} 0 ${PI/2}" xyz="-0.1 0.05 -0.1" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Gripper_arm1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="${PI/2} 0 ${PI/2}" xyz="-0.1 0.05 -0.1" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Gripper_arm1.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="red"/>
    </visual>
 </link>

<!--description of robot arm2 (cutting arm)-->

 <joint name="chassis__arm2" type="revolute">
    <origin xyz="-0.5 0 0.75" rpy="0 0 0"  />
    <parent link="chassis"/>
    <child link="link1_arm2"/>
    <axis xyz="0 0 1" rpy="0 0 0" />
    <limit effort="1000" lower="-0.56" upper="0.56" velocity="0.5" />
 </joint>

 <transmission name="trans_chassis__arm2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="chassis__arm2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_chassis__arm2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="link1_arm2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	   <cylinder length="0.3" radius="0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	   <cylinder length="0.3" radius="0.2"/>
      </geometry>
      <material name="blue"/>
    </visual>
      
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="35"/>
      <cylinder_inertia m="35" r="0.2" h="0.3"/>
    </inertial>

    <inertial>
        <mass value="8" />
        <origin rpy="${PI/2} ${PI/2} ${PI/2}" xyz="-1.1 -0.2 0.2" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
        <origin rpy="${PI/2} ${PI/2} ${PI/2}" xyz="-1.1 -0.2 0.2" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Lower_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
        <origin rpy="${PI/2} ${PI/2} ${PI/2}" xyz="-1.1 -0.2 0.2" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Lower_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
        <material name="blue"/>
    </visual>
 </link>

 <joint name="joint1_arm2" type="revolute">
    <origin xyz="-1 0 0" rpy="0 0 0"  />
    <parent link="link1_arm2"/>
    <child link="link2_arm2"/>
    <axis xyz="0 0 1" rpy="0 0 0" />
    <limit effort="1000" lower="-1" upper="1" velocity="0.3" />
 </joint>  

 <transmission name="trans_joint1_arm2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1_arm2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint1_arm2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="link2_arm2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	   <cylinder length="0.3" radius="0.05"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	   <cylinder length="0.3" radius="0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
      
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="3"/>
      <cylinder_inertia m="3" r="0.05" h="0.3"/>
    </inertial>
 
    <inertial>
        <mass value="5" />
        <origin rpy="0 ${PI/2} 0" xyz="-0.4 -0.15 -0.1" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
       <origin rpy="0 ${PI/2} 0" xyz="-0.4 -0.15 -0.1" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
      <origin rpy="0 ${PI/2} 0" xyz="-0.4 -0.15 -0.1" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/Upper_arm_left.stl" scale="0.005 0.005 0.005"/>
        </geometry>
      <material name="blue"/>
    </visual>
 </link>

 <joint name="joint2_arm2" type="revolute">
    <origin xyz="-0.37 0 0" rpy="0 0 0"  />
    <parent link="link2_arm2"/>
    <child link="sawblade"/>
    <axis xyz="0 0 1" rpy="0 0 0" />
    <limit effort="1000" lower="0" upper="${PI}" velocity="5" />
 </joint> 

 <transmission name="trans_joint2_arm2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2_arm2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_joint2_arm2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
 </transmission>

 <link name="sawblade">
    <inertial>
        <mass value="4" />
        <origin rpy="${PI/2} 0 0" xyz="0 0 -0.15" />
        <inertia ixx="13.235" ixy="0" ixz="0" iyy="13.235" iyz="0" izz="9.655" />
    </inertial>

    <collision>
       <origin rpy="${PI/2} 0 0" xyz="0 0 -0.15" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/saw.stl" scale="0.005 0.005 0.005"/>
        </geometry>
    </collision>

    <visual>
      <origin rpy="${PI/2} 0 0" xyz="0 0 -0.15" />
        <geometry>
          <mesh filename="package://mrm_description/meshes/saw.stl" scale="0.005 0.005 0.005"/>
        </geometry>
      <material name="brown"/>
    </visual>
 </link>
<!--end of description of robot-->

<!--gazebo plugin-->
 <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    </plugin>
 </gazebo>
 
</robot>
