joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

leftWheel_effort_controller:
  type: effort_controllers/JointEffortController
  joint: left_wheel_hinge
  pid: {p: 100.0, i: 0.1, d: 10.0}
rightWheel_effort_controller:
  type: effort_controllers/JointEffortController
  joint: right_wheel_hinge
  pid: {p: 100.0, i: 0.1, d: 10.0}
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: chassis__arm1
  pid: {p: 2000.0, i: 100, d: 500.0}
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1_arm1
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2_arm1
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: joint3_arm1
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: gripper_right
  pid: {p: 2000.0, i: 100, d: 500.0}
joint8_position_controller:
  type: position_controllers/JointPositionController
  joint: gripper_left
  pid: {p: 2000.0, i: 100, d: 500.0}
joint9_position_controller:
  type: position_controllers/JointPositionController
  joint: chassis__arm2
  pid: {p: 2000.0, i: 100, d: 500.0}
joint10_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1_arm2
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint11_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2_arm2
  pid: {p: 2000.0, i: 100, d: 500.0}
