joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm:
    type: position_controllers/JointTrajectoryController
    joints:
        - chassis__arm1
        - joint1_arm1
        - joint2_arm1
        - joint3_arm1
        - gripper_left
        - gripper_right
        - chassis__arm2
        - joint1_arm2
        - joint2_arm2

    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        chassis__arm1: {trajectory: 0.1, goal: 0.1}
        joint1_arm1: {trajectory: 0.1, goal: 0.1}
        joint2_arm1: {trajectory: 0.1, goal: 0.1}
        joint3_arm1: {trajectory: 0.1, goal: 0.1}
        gripper_left: {trajectory: 0.1, goal: 0.1}
        gripper_right: {trajectory: 0.1, goal: 0.1}
        chassis__arm2: {trajectory: 0.1, goal: 0.1}
        joint1_arm2: {trajectory: 0.1, goal: 0.1}
        joint2_arm2: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
